spring:
  application:
    name: final project
  messages:
    basename: i18n/messages
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/orclpdb
    username: hr
    password: hr
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
